[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 2

[fuzz]
runs = 1_000
fail_on_revert = true

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHEREUM_API_KEY}" }
optimism = { key = "${OPTIMISM_API_KEY}" }

[doc]
title = "MTA Buyback and Burn Contract"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config